services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ecouser
      POSTGRES_PASSWORD: ecopass
      POSTGRES_DB: ecogrid
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecouser -d ecogrid"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ../backend
    environment:
      POSTGRES_USER: ecouser
      POSTGRES_PASSWORD: ecopass
      POSTGRES_DB: ecogrid
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  web:
    build: ../frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  dbdata: